### ISSUE TITLE
Game crashes because of the new version of GalaxySpace

### ISSUE THREAD

**Issue by R3alRezentiX** [BlesseNtumble/GalaxySpace#614] opened 2022-08-03 05:09 UTC
------------------------------------------------------------------------
1. Minecraft version: **1.12.2 Forge 14.23.5.2860**
2. Galacticraft version: **4.0.2.280**
3. GalaxySpace version: **2.0.19**
4. AsmodeusCore version: **0.0.31** 
5. Side (Single player (SSP), Multiplayer (SMP), or SSP opened to LAN (LAN)): **(not applicable)**
6. Other add-ons: **-**
------------------------------------------------------------------------
Description of the issue:
With the new 2.0.19 version of GalaxySpace my modpack crashes. The crash seem to be caused by Alpha Centauri System.
If I use the 2.0.18 version, game doesn't crash.
------------------------------------------------------------------------
Attached log file (or url on pastebin.com):
https://pastebin.com/q8f6yecj
------------------------------------------------------------------------

**Comment by CaveJohnson376** [comment] 2022-08-03 05:24
duplicate of #600

**Comment by killerkalamari** [comment] 2022-08-04 01:33
> duplicate of #600

Right now AsmodeusCore version 0.0.31 is the latest, so this is not a dup.

EDIT: Found a different workaround: Use Galacticraft Legacy 4.0.2.284 instead of Galacticraft 4.0.2.280. Download here: https://www.curseforge.com/minecraft/mc-mods/galacticraft-legacy

**Comment by killerkalamari** [comment] 2022-08-04 02:17
Attached: Log with only Galacticraft and GS (1.12.2, 4.0.2.280, 2.0.19, 0.31). 
[crash-2022-08-03_18.29.33-client.txt](https://github.com/BlesseNtumble/GalaxySpace/files/9256155/crash-2022-08-03_18.29.33-client.txt)

**Closed as completed** 2022-08-22 02:19 UTC
